"""Justification-based Truth Maintenance System.

Foundations v1.0 section 5. The frozen baseline's sections 21.3 (state
dependency graph), 21.4 (selective propagation) and 21.5 (state
invalidation) are describing a JTMS (Doyle, 1979) point for point --
including the instinct to mark an invalidated belief STALE rather than
FAILED, which is exactly a JTMS labelling a node OUT without deleting it.

Two properties are why this is worth implementing rather than hand-rolling
a propagation scheme:

1. A node labelled OUT is not deleted. If the evidence that invalidated it
   is later retracted, the node returns to IN automatically. Hand-rolled
   invalidation almost always deletes, which is unrecoverable.

2. `explain()` walks the justification network to produce the causal chain
   behind any belief. This is what makes `caused_by` in the Experiment 001
   event trace *generated by the mechanism* rather than manually attached
   by the code that happens to emit the event -- a materially stronger
   guarantee, because a hand-attached causal link can be wrong while
   looking right.

Non-monotonic justifications (via `out_list`) admit networks with no
stable labelling. We detect oscillation and raise rather than silently
returning whichever state the loop stopped on.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Iterable


class Label(Enum):
    IN = "IN"
    OUT = "OUT"

    def __str__(self) -> str:
        return self.value


class JTMSError(RuntimeError):
    """Raised when the network admits no stable labelling."""


@dataclass(frozen=True)
class Justification:
    """A reason for believing a node.

    Valid when every node in `in_list` is IN and every node in `out_list`
    is OUT. A justification with both lists empty is a *premise*: always
    valid, believed unconditionally.
    """

    id: str
    consequent: str
    in_list: tuple[str, ...] = ()
    out_list: tuple[str, ...] = ()
    rationale: str = ""

    @property
    def is_premise(self) -> bool:
        return not self.in_list and not self.out_list


@dataclass
class Node:
    id: str
    label: Label = Label.OUT
    justifications: list[Justification] = field(default_factory=list)
    #: The justification currently making this node IN, if any. This is
    #: what `explain()` follows, so it must reflect the *actual* support,
    #: not merely the first justification added.
    support: Justification | None = None


class JTMS:
    """Minimal justification-based truth maintenance.

    Labelling is computed to a fixpoint over the whole network. For the
    scale Experiment 001 operates at (tens of nodes) this is correct and
    fast; it is not the incremental algorithm a large system would use,
    and that trade is deliberate -- correctness over cleverness while the
    mechanism is still being proven.
    """

    MAX_PASSES = 100

    def __init__(self) -> None:
        self._nodes: dict[str, Node] = {}

    # -- construction -------------------------------------------------

    def node(self, node_id: str) -> Node:
        if node_id not in self._nodes:
            self._nodes[node_id] = Node(id=node_id)
        return self._nodes[node_id]

    def premise(self, node_id: str, *, rationale: str, justification_id: str | None = None) -> Justification:
        """Believe `node_id` unconditionally."""
        return self.justify(
            node_id, in_list=(), out_list=(), rationale=rationale, justification_id=justification_id
        )

    def justify(
        self,
        consequent: str,
        *,
        in_list: Iterable[str] = (),
        out_list: Iterable[str] = (),
        rationale: str,
        justification_id: str | None = None,
    ) -> Justification:
        """Add a reason for believing `consequent`, then relabel."""
        if not rationale:
            raise ValueError("every justification requires a rationale")

        in_tuple = tuple(in_list)
        out_tuple = tuple(out_list)
        for antecedent in in_tuple + out_tuple:
            self.node(antecedent)

        target = self.node(consequent)
        jid = justification_id or f"j{len(self._all_justifications()) + 1}"
        justification = Justification(
            id=jid,
            consequent=consequent,
            in_list=in_tuple,
            out_list=out_tuple,
            rationale=rationale,
        )
        target.justifications.append(justification)
        self._relabel()
        return justification

    def retract(self, justification_id: str) -> None:
        """Remove a justification and relabel.

        Nodes that lose their last valid support become OUT -- they are not
        removed, so a later justification can restore them.
        """
        for node in self._nodes.values():
            node.justifications = [j for j in node.justifications if j.id != justification_id]
        self._relabel()

    # -- inspection ---------------------------------------------------

    def label(self, node_id: str) -> Label:
        return self.node(node_id).label

    def is_in(self, node_id: str) -> bool:
        return self.label(node_id) is Label.IN

    def support(self, node_id: str) -> Justification | None:
        return self.node(node_id).support

    def explain(self, node_id: str) -> list[Justification]:
        """The causal chain supporting `node_id`, antecedents first.

        Returns [] for a node that is OUT -- an unsupported belief has no
        explanation, which is a meaningful answer rather than an error.

        This is the source of `caused_by` in the event trace. Because it
        is derived from the live justification network, it cannot drift
        away from the reasoning that actually produced the belief.
        """
        chain: list[Justification] = []
        seen: set[str] = set()

        def walk(current: str) -> None:
            if current in seen:
                return
            seen.add(current)
            node = self.node(current)
            if node.label is not Label.IN or node.support is None:
                return
            for antecedent in node.support.in_list:
                walk(antecedent)
            if node.support not in chain:
                chain.append(node.support)

        walk(node_id)
        return chain

    def nodes(self) -> dict[str, Node]:
        return dict(self._nodes)

    # -- labelling ----------------------------------------------------

    def _all_justifications(self) -> list[Justification]:
        return [j for node in self._nodes.values() for j in node.justifications]

    def _valid(self, justification: Justification) -> bool:
        return all(self.is_in(n) for n in justification.in_list) and all(
            not self.is_in(n) for n in justification.out_list
        )

    def _relabel(self) -> None:
        """Recompute labels to a fixpoint.

        Starts every node OUT and grows the IN set. For purely monotonic
        networks this reaches the unique minimal model. With `out_list`
        justifications a network can oscillate; we bound the passes and
        raise rather than return an arbitrary snapshot.
        """
        for node in self._nodes.values():
            node.label = Label.OUT
            node.support = None

        for _ in range(self.MAX_PASSES):
            changed = False
            for node in self._nodes.values():
                supporting = next(
                    (j for j in node.justifications if self._valid(j)), None
                )
                should_be_in = supporting is not None
                currently_in = node.label is Label.IN

                if should_be_in != currently_in:
                    node.label = Label.IN if should_be_in else Label.OUT
                    node.support = supporting
                    changed = True
                elif should_be_in and node.support is not supporting:
                    node.support = supporting
                    changed = True

            if not changed:
                return

        raise JTMSError(
            "no stable labelling after "
            f"{self.MAX_PASSES} passes; the network likely contains an "
            "odd non-monotonic cycle"
        )
