"""Seed the journal with decisions actually made while building v0.1.

Every entry is marked retrospective: the decision predates the journal,
so its prediction was written by someone who already knew how the build
was going. Calibration excludes them by default.

What makes them worth recording anyway is that each prediction is
*forward*-looking -- about rework that has not happened yet -- so they
become scoreable later without ever having been graded on hindsight.

Run once: python journal/seed.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from escapement.belief.labels import BeliefLabel as B  # noqa: E402
from escapement.journal.models import DecisionEntry, Prediction  # noqa: E402
from escapement.journal.store import Journal  # noqa: E402

ENTRIES = [
    DecisionEntry(
        id="d001-ordinal-beliefs-not-floats",
        question="How should belief strength be represented?",
        chosen="five ordered labels (RULED_OUT..ESTABLISHED)",
        alternatives=("point probabilities", "interval floats", "Dempster-Shafer masses"),
        rationale=(
            "A point probability cannot distinguish uncertainty from ignorance: P=0.5 "
            "asserts 'equally likely', which is a strong claim, not an absence of "
            "information. That indistinguishability is how the baseline's named False "
            "precision risk enters."
        ),
        evidence=("foundations-v1.0-section-4", "baseline-section-35-false-precision"),
        prediction=Prediction(
            claim="ordinal labels will prove sufficient through Experiment 002 without needing floats",
            confidence=B.LIKELY,
            resolution_criteria=(
                "BROKE if any experiment through 002 requires a float belief to express "
                "something labels cannot, or if ties become so pervasive that the id "
                "tie-break decides outcomes rather than merely ordering them"
            ),
        ),
        retrospective=True,
        tags=("belief", "foundations"),
    ),
    DecisionEntry(
        id="d002-jtms-not-hand-rolled-invalidation",
        question="How should belief invalidation and provenance work?",
        chosen="implement a justification-based truth maintenance system",
        alternatives=(
            "hand-rolled dependency propagation",
            "recompute everything on change",
            "no invalidation at v0.1",
        ),
        rationale=(
            "Baseline sections 21.3-21.5 describe a JTMS point for point, including the "
            "instinct to mark state STALE rather than FAILED, which is exactly a JTMS "
            "labelling a node OUT without deleting it. A real JTMS also makes explain() "
            "derive causal chains from the live network, so caused_by in the trace is "
            "generated by the mechanism rather than attached by hand -- and a "
            "hand-attached causal link can be wrong while looking right."
        ),
        evidence=("foundations-v1.0-section-5", "baseline-sections-21.3-21.5"),
        prediction=Prediction(
            claim="the JTMS will not need replacing or substantially rewriting within the next 20 journal entries",
            confidence=B.LIKELY,
            resolution_criteria=(
                "BROKE if jtms/core.py is rewritten, replaced, or gains a second parallel "
                "invalidation path before entry d021"
            ),
        ),
        retrospective=True,
        tags=("jtms", "foundations"),
    ),
    DecisionEntry(
        id="d003-rename-quantum-to-continuum",
        question="Should the research line keep the name Quantum Escapement?",
        chosen="rename to Escapement-Continuum",
        alternatives=("keep Quantum Escapement", "Escapement-Next", "Escapement-Labs"),
        rationale=(
            "The baseline's own risk register names Quantum branding confusion a top risk, "
            "mitigated only by always saying 'quantum-inspired'. A rename removes the risk "
            "class instead of managing it forever. Foundations section 10 also documented "
            "three places where the metaphor causes engineering errors, not merely PR "
            "confusion -- interference cannot exist in classical probability."
        ),
        evidence=("baseline-section-35-quantum-branding", "foundations-v1.0-section-10"),
        prediction=Prediction(
            claim="nobody will attempt to add amplitude, phase, or complex-valued belief arithmetic to the codebase",
            confidence=B.LIKELY,
            resolution_criteria=(
                "BROKE if any commit introduces a field or function implying quantum "
                "formalism (amplitude, phase, wavefunction, interference arithmetic)"
            ),
        ),
        retrospective=True,
        tags=("naming", "risk"),
    ),
    DecisionEntry(
        id="d004-package-layout-follows-baseline",
        question="Six modules under quantum/, or the baseline's ten under escapement/?",
        chosen="baseline section 27 layout: escapement/ with ten packages",
        alternatives=("six modules under quantum/ as the contract originally specified",),
        rationale=(
            "An independent review found the contract's precondition P4 contradicted "
            "baseline section 27. The contract's own precedence rule says the baseline wins "
            "and the contract is defective. Amended P4 rather than working around it."
        ),
        evidence=("primitive-review-finding-0", "baseline-section-27"),
        prediction=Prediction(
            claim="the ten-package layout will hold through Experiment 005 without restructuring",
            confidence=B.PLAUSIBLE,
            resolution_criteria="BROKE if packages are added, removed or renamed before Experiment 005 ships",
        ),
        retrospective=True,
        tags=("structure", "contract"),
    ),
    DecisionEntry(
        id="d005-candidate-lifecycle-for-criterion-11",
        question="How can a retained alternative be distinguished from an eliminated one?",
        chosen="explicit CANDIDATE/ELIMINATED/RETAINED/COMMITTED lifecycle, marking rather than removing",
        alternatives=(
            "remove dominated strategies as baseline section 17 says",
            "a boolean retained flag",
        ),
        rationale=(
            "Criterion 11 was not representable without it: the model could satisfy the "
            "criterion's letter using an already-dead candidate, a vacuous pass under clause "
            "A1. Baseline section 17 says remove; removal destroys exactly the distinction "
            "the criterion tests, so we mark instead -- matching the same STALE-not-FAILED "
            "instinct in section 21.5."
        ),
        evidence=("primitive-review-finding-5.1", "contract-criterion-11", "contract-clause-A1"),
        prediction=Prediction(
            claim="deriving retained alternatives from candidate status will prevent any future vacuous pass of criterion 11",
            confidence=B.LIKELY,
            resolution_criteria=(
                "BROKE if a reviewer finds a way to satisfy criterion 11 with a candidate "
                "that was not genuinely retained at commit time"
            ),
        ),
        retrospective=True,
        tags=("strategy", "contract"),
    ),
    DecisionEntry(
        id="d006-decision-journal-not-literal-self-hosting",
        question="Should Continuum be used to build Continuum?",
        chosen="a decision journal recording decisions about Continuum, advisory only",
        alternatives=(
            "literal self-hosting: route development through run_episode()",
            "no self-hosting until after Experiment 005",
        ),
        rationale=(
            "Literal self-hosting fails three ways: Continuum cannot write code yet so it "
            "would be narration rather than evidence; it makes the correlation problem "
            "structural in a project where independent review has twice found defects in "
            "self-authored work; and it inverts baseline section 35's own mitigation, which "
            "requires empirical calibration before policy mutation. The journal produces an "
            "auditable claim instead of a circular one."
        ),
        evidence=(
            "baseline-section-35-self-optimization",
            "foundations-v1.0-section-8",
            "roadmap-step-1",
        ),
        prediction=Prediction(
            claim="the journal will reach 30 non-retrospective entries before any entry has to be voided as unfalsifiable",
            confidence=B.PLAUSIBLE,
            resolution_criteria=(
                "BROKE if an entry has to be VOIDED because its resolution_criteria turned "
                "out not to be checkable, before 30 real entries exist"
            ),
        ),
        retrospective=True,
        tags=("journal", "method", "rlm"),
    ),
    DecisionEntry(
        id="d007-mvt-stopping-not-fixed-threshold",
        question="When should information gathering stop?",
        chosen="Marginal Value Theorem: stop when best EVI falls below the return of proceeding",
        alternatives=("a configured EVI threshold", "a fixed max_questions cap", "SPRT thresholds"),
        rationale=(
            "A configured threshold can be chosen after the fact to fit, which is a clause A1 "
            "vacuous pass. Under Charnov's theorem the bar is the opportunity cost of the "
            "alternative, so it is computed rather than set. SPRT is the better long-run "
            "answer but needs calibrated likelihoods that do not exist yet."
        ),
        evidence=("foundations-v1.0-section-3.3", "contract-criterion-8"),
        prediction=Prediction(
            claim="MVT will remain the stopping rule until calibration data justifies SPRT",
            confidence=B.PLAUSIBLE,
            resolution_criteria="BROKE if the stopping rule changes before 100 resolved predictions exist",
        ),
        retrospective=True,
        tags=("evi", "foundations"),
    ),
    DecisionEntry(
        id="d008-repo-public-at-alpha",
        question="Should the research repository be public at 0.1.0-alpha?",
        chosen="public",
        alternatives=("private until Experiment 001 is independently scored",),
        rationale=(
            "User decision. The counter-argument was that an unscored first experiment in a "
            "public repo invites 'Escapement has a v2' inference; mitigated by explicit "
            "research-stage framing in README and ROADMAP rather than by secrecy."
        ),
        evidence=("user-decision",),
        prediction=Prediction(
            claim="no external party will cite Continuum as a shipped or validated successor to v1 before Experiment 002 completes",
            confidence=B.PLAUSIBLE,
            resolution_criteria=(
                "BROKE if Continuum is publicly described as production-ready, as replacing "
                "v1, or as having proven its claims, before Experiment 002 completes"
            ),
        ),
        retrospective=True,
        tags=("release", "risk"),
    ),
]


def main() -> int:
    journal = Journal(Path(__file__).resolve().parent / "decisions.jsonl")
    existing = journal.load()
    added = 0
    for entry in ENTRIES:
        if entry.id in existing:
            continue
        journal.append(entry)
        added += 1
    print(f"seeded {added} entries ({len(existing) + added} total)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
